select * from PC_HEVODATA_DB.PUBLIC.CLEANED_CUSTOMERS;
select * from PC_HEVODATA_DB.PUBLIC.CLEANED_ORDERS;
select * from PC_HEVODATA_DB.PUBLIC.CLEANED_PRODUCTS;
select * from PC_HEVODATA_DB.PUBLIC.CLEANED_FINAL_DATA;
